{
 "title": "JVM Overview - Prometheus",
 "description": "Dashboard for JVM metrics with Prometheus / JMX Exporter",
 "tags": [
  "JVM",
  "prometheus"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_labels, namespace)"
    }
   },
   {
    "name": "Service",
    "query": {
     "query": "label_values(kube_service_labels{namespace=~\"^$Namespace$\"}, service)"
    }
   },
   {
    "name": "Pod",
    "query": {
     "query": "label_values(kube_pod_labels{namespace=~\"^$Namespace$\",pod=~\"^$Service-[a-z0-9]+-[a-z0-9]+\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Memory used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{namespace=~\"^$Namespace$\",service=~\"^$Service$\",pod=~\"^$Pod$\"}",
     "legendFormat": "[{{area}}:{{id}}] {{pod}}"
    }
   ]
  },
  {
   "title": "Threads used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_live_threads{namespace=~\"^$Namespace$\",service=~\"^$Service$\",pod=~\"^$Pod$\"}",
     "legendFormat": "{{pod}} [live]"
    },
    {
     "expr": "jvm_threads_daemon_threads{namespace=~\"^$Namespace$\",service=~\"^$Service$\",pod=~\"^$Pod$\"}",
     "legendFormat": "{{pod}} [daemon]"
    }
   ]
  },
  {
   "title": "Class loading",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_classes_loaded_classes{namespace=~\"^$Namespace$\",service=~\"^$Service$\",pod=~\"^$Pod$\"}",
     "legendFormat": "{{pod}} [loaded]"
    }
   ]
  },
  {
   "title": "GC time / 1 min. rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{namespace=~\"^$Namespace$\",service=~\"^$Service$\",pod=~\"^$Pod$\"}[1m])",
     "legendFormat": "{{pod}} [{{gc}}]"
    }
   ]
  },
  {
   "title": "GC count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_gc_collection_seconds_count{namespace=~\"^$Namespace$\",service=~\"^$Service$\",pod=~\"^$Pod$\"}",
     "legendFormat": "{{pod}} [{{gc}}]"
    }
   ]
  }
 ]
}