{
 "title": "Kubernetes ReplicaSet - Prometheus",
 "description": "Dashboard for Kubernetes replicaset with Prometheus.",
 "tags": [
  "kubernetes",
  "prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "Namespace",
    "query": "label_values(kube_namespace_labels, namespace)"
   },
   {
    "name": "ReplicaSet",
    "query": "label_values(kube_replicaset_labels{namespace=~\"^$Namespace$\"}, replicaset)"
   }
  ]
 },
 "panels": [
  { "title": "Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pods",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum( kube_replicaset_status_replicas_available{namespace=~\"^$Namespace$\",replicaset=~\"^$ReplicaSet\"} )"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",namespace=~\"^$Namespace$\",pod_name=~\"^$ReplicaSet-[a-z0-9]+\"}[2m])) / sum (kube_pod_container_resource_requests_cpu_cores{namespace=~\"^$Namespace$\",pod=~\"^$ReplicaSet-[a-z0-9]+\"}) * 100"
    }
   ]
  },
  {
   "title": "CPU Usage (2m avg)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",namespace=~\"^$Namespace$\",pod_name=~\"^$ReplicaSet-[a-z0-9]+\"}[2m])) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Updated",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum( kube_replicaset_status_replicas_updated{namespace=~\"^$Namespace$\",replicaset=~\"^$ReplicaSet\"} )"
    }
   ]
  },
  {
   "title": "Unavailable",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum( kube_replicaset_status_replicas_unavailable{namespace=~\"^$Namespace$\",replicaset=~\"^$ReplicaSet\"} )"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",namespace=~\"^$Namespace$\",pod_name=~\"^$ReplicaSet-[a-z0-9]+\"}[2m]))"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (kube_pod_container_resource_requests_cpu_cores{container!=\"istio-proxy\",namespace=~\"^$Namespace$\",pod=~\"^$ReplicaSet-[a-z0-9]+\"})"
    }
   ]
  },
  {
   "title": "Limits",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (kube_pod_container_resource_limits_cpu_cores{container!=\"istio-proxy\",namespace=~\"^$Namespace$\",pod=~\"^$ReplicaSet-[a-z0-9]+\"})"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum( kube_replicaset_status_replicas_updated{namespace=~\"^$Namespace$\",replicaset=~\"^$ReplicaSet\"} )",
     "legendFormat": "updated"
    },
    {
     "expr": "sum( kube_replicaset_status_replicas_available{namespace=~\"^$Namespace$\",replicaset=~\"^$ReplicaSet\"} )",
     "legendFormat": "available"
    },
    {
     "expr": "sum( kube_replicaset_status_replicas_unavailable{namespace=~\"^$Namespace$\",replicaset=~\"^$ReplicaSet\"} )",
     "legendFormat": "unavailable"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 8 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",namespace=~\"^$Namespace$\",pod_name=~\"^$ReplicaSet-[a-z0-9]+\"}) / sum (kube_pod_container_resource_requests_memory_bytes{namespace=~\"^$Namespace$\",pod=~\"^$ReplicaSet-[a-z0-9]+\"}) * 100"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",namespace=~\"^$Namespace$\",pod_name=~\"^$ReplicaSet-[a-z0-9]+\"}) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 13 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",namespace=~\"^$Namespace$\",pod_name=~\"^$ReplicaSet-[a-z0-9]+\"})"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 13 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (kube_pod_container_resource_requests_memory_bytes{container!=\"istio-proxy\",namespace=~\"^$Namespace$\",pod=~\"^$ReplicaSet-[a-z0-9]+\"})"
    }
   ]
  },
  {
   "title": "Limits",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 13 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (kube_pod_container_resource_limits_memory_bytes{container!=\"istio-proxy\",namespace=~\"^$Namespace$\",pod=~\"^$ReplicaSet-[a-z0-9]+\"})"
    }
   ]
  },
  { "title": "Ingress Controller", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Requests (2m avg)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum (rate (nginx_ingress_controller_requests{namespace=~\"^$Namespace$\",service=~\"^$ReplicaSet$\"}[2m]) ) by (status)",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Network I/O (2m avg)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",name=~\"^k8s_.*\",namespace=~\"^$Namespace$\",pod_name=~\"^$ReplicaSet-[a-z0-9]+\"}[2m])) by (pod_name)",
     "legendFormat": "-> {{ pod_name }}"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\",name=~\"^k8s_.*\",namespace=~\"^$Namespace$\",pod_name=~\"^$ReplicaSet-[a-z0-9]+\"}[2m])) by (pod_name)",
     "legendFormat": "<- {{ pod_name }}"
    },
    {
     "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",name=~\"^k8s_.*\",namespace=~\"^$Namespace$\",pod_name=~\"^$ReplicaSet-[a-z0-9]+\"}[2m]))",
     "legendFormat": "-> {{ $ReplicaSet }}"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\",name=~\"^k8s_.*\",namespace=~\"^$Namespace$\",pod_name=~\"^$ReplicaSet-[a-z0-9]+\"}[2m]))",
     "legendFormat": "<- {{ $ReplicaSet }}"
    }
   ]
  }
 ]
}